yrosseel/lavaan

DESCRIPTION, tests/testthat.R, tests/testthat/helper-skip_level.R, tests/testthat/test-lav_matrix.R, tests/testthat/test-skip_example.R
I emailed with an update on adding unit tests (issue #56), but figured I would submit a pull request so you can see the changes along with code diffs.
* testthat helper script to skip a test, depending on the environment variable LAV_TEST_LEVEL [here](https://github.com/yrosseel/lavaan/compare/master...machow:tests?expand=1#diff-7dbf5dd485b1b794b591b64fc55dffe0R1).
* example of skipping a test [here](https://github.com/yrosseel/lavaan/compare/master...machow:tests?expand=1#diff-774242af4215a72ea001c92782ec21c2R1).
I'm happy to rename things or make changes (note that lavaan on master seems to be failing on travis-ci based on the R build check giving warnings).
=> Add unit tests

tests/testthat/test_lav_mvnorm.R
I added a file to /tests that can be checked automatically by the testthat package.  The bottom line is a commented command that can be run to test only this file.  It should remain commented so that recursion does not produce a spurious error).
The file only includes tests for the family of tests (1.) that returns (sums of) (log-)densities, comparing the output from several options with the manually coded use of mvtnorm and mnormt packages.  If I find software that returns derivatives, I could add those tests, but for now I will simply compare the source code to the documentation. 
Terry
=> add lav_mvnorm tests

R/lav_object_inspect.R
Here is a small change so that coef() works with objects of class blavaan and others that contain lavaan. Otherwise, there is an infinite recursion whereby coef() calls lav_object_inspect_est(), which calls coef(), etc...
Ed
=> allow coef() to work on classes that contain lavaan

R/lav_predict.R, man/lavPredict.Rd
This exposes the ETA argument to users in lavPredict(), so that it is possible to obtain ov predictions that include custom values of ETA. It seems like the underlying function, lav_predict_yhat, was already set up to do this, and the user just needs a way to get there via an exported function. And this will be personally helpful for evaluating some marginal likelihoods in the non-normal case.
Also, fwiw, it looks like lavPredict() with type="fy" is broken. I started to look at fixing it, but then I wasn't sure whether it was supposed to work (especially because type="fy" is not documented). I can go back to try and fix it if you want.
Thanks,
Ed
=> add ETA argument to lavPredict(), for specified lv values

R/lav_object_methods.R, R/lav_partable_merge.R, R/xxx_lavaan.R
`lav_object_extended(..., do.fit = FALSE)` returns a parameter table that is meant for use in `lavTestScore()` and `modindices()`, so in the added rows, it has:
- `group == ""`
- `plabel == ""`
- `user == 10`, except existing parameters are `user == 0`
I borrow `group` labels from the `block` column, and delete the `user` column so that it is automatically repopulated.  Not sure if the empty strings in `plabel` have any consequence.
=> update(fit, add=...) calls lav_object_extended()

R/lav_modification.R, R/lav_object_generate.R, R/lav_object_methods.R, R/lav_print.R, R/lav_test_score.R, man/lavInspect.Rd, man/lavTestScore.Rd, man/lavaan-class.Rd, man/standardizedSolution.Rd
I was not able to hack the `update()` function, so I simply borrowed source code from `lavaan:::lav_object_extended()`. But I did notice that `update()` should check whether `slot*` arguments were used in the `@call`.
Here are the other changes I made for score tests with multiple imputations:
- I added a `partable=` argument to `standardizedSolution()` so I could add SEPCs
- I need `ADD` to have a `group` column in `lavaan:::lav_object_extended()`
- I check for columns in `lavaan:::print.lavaan.parameterEstimates()` associated with lavaan.mi objects
- I assign an extended parameter table to `LIST` in lav_test_score.R so that an EPC will also be calculated for any added parameters
On line 87 of lav_test_score.R, I note that an assignment might belong within an `if` scope. And there are a …
=> updates for lavaan.mi score tests

R/lav_fit_measures.R, man/lavTestScore.Rd
I added a parameter-table example to `lavTestScore(add=)` so users know what they need (may be more convenient that syntax in simulations).
I also think ECVI is valid in multigroup and MACS models.  I attached the paper discussing the multigroup issue, and I just don't think the mean-structure issue is relevant (just a simplification in the Browne & Cudeck article).
[Dudgeon.2004.MultipleSampleRMSEAadj.pdf](https://github.com/yrosseel/lavaan/files/1943827/Dudgeon.2004.MultipleSampleRMSEAadj.pdf)
=> update lavTestScore help page

R/xxx_lavaanList.R
Sorry it looks like a bunch of changes.  I have my editor set to delete extra white space at the end of lines. 
The only actual change was on line 173, where `lavaanList()` assumed the order of variables in `DATA` corresponded to the order of model variables in `@pta`.  I changed it to use variable names instead of indices to avoid the issue, but perhaps you will prefer to fix it another way.  This was causing problems when fitting a model to categorical indicators in `semTools::runMI()` when there were additional variables in the list of imputed data sets.
=> fix lavaanList bug 

R/lav_standardize.R
`cov.x` is only used `if (conditional.x)`, so I changed 2 lines to extract it only in that condition.  A side effect of extracting it unconditionally is an error with `lavaan.mi` objects, which (like `lavaanList` objects) lack the `@SampleStats` slot.  Because `runMI()` sets `fixed.x=FALSE` and `conditional.x=FALSE`, this will never be a problem for appropriately standardizing pooled estimates.  But I think this solution is not only the easiest to prevent the error, but a good general solution because `cov.x` is only needed `if (conditional.x)`.
I only changed lines 458 and 470; the other "changes' are just trailing whitespace my editor automatically deletes when saving files.
=> in lav_standardize_all, only extract SampleStats@cov.x if conditional.x

R/lav_polychor.R, R/lav_polyserial.R
Following the [lavaan-forum post](https://groups.google.com/d/msg/lavaan/b27N4UTT9is/IDI2cO3rAgAJ), I added a starting value of zero for polyserial and polychoric correlations that have no observations:
```
if(is.na(rho.init)) {
rho.init <- 0.0
}
```
But if `rho.init` is missing because there is no observed data (or only n=1) for a pair of variables, then I imagine the `lavCor()` estimation will probably fail anyway.  If that is the case, let me know if I should change the pull request to this:
```
if(is.na(rho.init)) {
stop('lavaan ERROR: The following pair of variables have no joint observations, ',
'so their polyserial/polychoric correlation cannot be estimated:\n', 
deparse(substitute(Y1)), ' and ', deparse(substitute(Y2)), "\n)
}
```
=> if rho.init is missing

DESCRIPTION, NAMESPACE
Hi there, 
When I installed (today) the package on my Debian machine (seeDetails below) I had a couple of issues related to functions that were not imported from `Methods`. I solved this by adding the ones included in this PR. Note that this PR is only few additions in the NAMESPACE and that the small addition is DESCRIPTION is totally up to you.
Anyway, many thanks for you work on this package! 
<details>
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid
Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
locale:
[1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_US.UTF-8 …
=> Import few more functions from methods. 

DESCRIPTION, R/00generic.R, R/lav_fit_measures.R, R/lav_modification.R, R/lav_object_inspect.R, R/lav_options.R, R/lav_test_score.R, R/xxx_lavaanList.R, man/fitMeasures.Rd, man/lavInspect.Rd, man/lavPredict.Rd, man/lavTestScore.Rd, man/lavaan-class.Rd, man/modificationIndices.Rd, man/parameterEstimates.Rd
In order to preserve the original values of the arguments specified by the user to `cfaList()` or `semList()` when storing the `@call` slot, I used `match.call()` instead of directly calling `lavaanList()` with eponymous argument names. 
To facilitate performing simulation studies that can compare the use of different information matrices when calculating score tests (I am involved with such a study by one of Craig Enders' grad students), I added an option to use the information requested when fitting the model.  By default, the expected information is requested, to preserve the current behavior (which is ideal, but it is still nice to be able to empirically verify that).
=> lavaanList wrappers and information for score tests

R/lav_test_score.R, man/lavTestScore.Rd, man/modificationIndices.Rd
Only one of these is necessary: the `$cumulative` table used the same order of rows as the `$uni` table, instead of sorting it, so the constraint labels did not match the tests.
The other changes are just things I would like to see :-)  
- Standardized EPCs in the `$epc` table
- An `epc` column in the `$uni` table when `add`ing parameters and `epc=TRUE` (matches `modindices()`).
It would take more cleverness than I have time for right now to add standardized EPCs to the `$uni` output, which would be nice, but I'd rather wait to see if you agree to add EPCs to `$uni` at all.
=> lavTestScore updates

R/lav_lavaanList_inspect.R, R/lav_object_inspect.R, man/lavInspect.Rd, man/lavListInspect.Rd
These will be useful in general, but I will need these options as I update `semTools` to work with MSEMs if I want to avoid referencing the `@Data` slot.
=> add inspect options for cluster sizes, count(s), and IDs

DESCRIPTION, R/lav_lavaanList_inspect.R, R/lav_residuals.R, man/lavResiduals.Rd
Here's some example code to check the `custom.rmr` argument.  It looks for a named `list` containing custom summaries, each of which is defined using a nested `list` containing either:
- logical `matrix` (for `$cov`) and/or `vector` (for `$mean`)
- numeric vector with indices for `$cov`) and/or `$mean`
- numeric `matrix` with row/column indices for `$cov` (as returned by `which(..., arr.ind = TRUE)`)
Also, any combination of upper/lower-triangle indices can be specified for `$cov`. The code below defines the same summary in 5 different ways to cycle through the possibilities with a single- and multiple-group model.
```
HS.model <- ' visual  =~ x1 + x2 + x3
textual =~ x4 + x5 + x6
speed   =~ x7 + x8 + x9 
'
fit <- cfa(HS.model, data = HolzingerSwineford1939, meanstructure = TRUE)
fitg <- …
```
=> last minute additions before sending to CRAN

R/lav_predict.R, R/lav_test_LRT.R
I forget when you would be on vacation, but this is the little change I remember we discussed at IMPS, in addition to anything else you would like to update before sending to CRAN so I can send semTools to CRAN (it relies on the new `@baseline` and `@baselineList` slots).
Additional change is just 2 FIXME comments in `lavPredict()`, about appending data to level-2 factor scores.  `semTools::plausibleValues()` currently returns level-2 factor scores with the `cluster.label` as an additional column, to facilitate a possible `merge()` with their original data. Perhaps you would want to do the same in `lavPredict()`, or perhaps you would want to already `merge()` into the full level-1 `@Data` (so the number or rows returned would differ if `append.data=TRUE` or `FALSE`) or `newdata`.  I'm …
=> extend lavTestLRT message about scaled diff test

R/lav_mvnorm_missing_h1.R
This is for the EM algorithm that finds the "H1" implied Mu and Sigma. In that code, there is a double use of the "tol" variable so that the tol argument supplied to the function gets overwritten later on.
I think this means that, if we are happy with tol=1e-05 as default, this bit of code will speed up after the fix. (and I might be sending more requests related to this code, because I have to run this repeatedly in blavaan when there is missing data.)
=> missing_h1 EM, avoid overwriting tol

R/lav_model_implied.R
lav_model_implied() currently only works with the delta parameterization, but blavaan will use theta parameterization for ordinal data. This change allows for theta parameterization.
=> deal with delta/theta parameterization in lav_model_implied

R/lav_modification.R
Using absolute values of EPC for misspecification decisions.
=> EPC absolute values for decisions

DESCRIPTION, R/lav_fit_measures.R, R/lav_test_browne.R
I left comments in the syntax I changed.  Essentially, sometimes the "unrestricted" (N)ACOV will have structure.  Not just in the dyad-level SRM matrix I am working on, but even in models for independent dyads (e.g., APIM), there will be certain (co)variances that are equal.  Thus, their (N)ACOV elements will be identical, making it NPD.  I hope you agree that using `MASS::ginv()` in this case is acceptable.  I can't think of a reason to add a general warning about doing so, since this would probably never happen in a context where we weren't aware of the structure in the h1 model.
I also noticed `baseline.model=` wasn't getting passed to the new CFI function.
=> try(solve(Gamma[[g]])) for Browne's test with constraints

R/lav_bootstrap.R
I would like to propose this minor change to `lav_bootstrap_internal()`.
When users call `bootstrapLavaan()` using a function that returns named vectors, the names will not be kept in the output, as shown in the following example:
``` r
opt_old <- options(width = 100)
library(lavaan)
#> This is lavaan 0.6-14
#> lavaan is FREE software! Please report any bugs.
set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)
model <- ' # direct effect
Y ~ c*X
M ~ a*X
Y ~ b*M
ab := a*b
total := c + (a*b)
'
fit <- sem(model, data = Data)
get_std <- function(x, ...) {
std <- lavaan::standardizedSolution(x, ...)
out <- std$est.std
names(out) <- lavaan::lav_partable_labels(std)
out
}
standardizedSolution(fit)
#>     lhs op     rhs label …
```
=> Keep the names, if any, in the output of bootstrapLavaan()

R/lav_cor.R, R/lav_print.R, man/lavCor.Rd
Would you be opposed to this feature?  I would find it useful for both `lavaan.mi` and `lavaan.srm`, so adding it here would save me the trouble of writing separate `print()` methods for each.  I basically just copied your code in `print.lavaan.list()`, but use `attributes()` rather than `attr()` to simultaneous delete both header and footer from the copy `y <- x`.
=> allow header/footer printing for vector/matrix

R/lav_predict.R
The blavaan multilevel testing continues! This pr addresses a lavPredict() bug when there are between-only variables. The data from those variables were not being included in the level 2 lv predictions.
The example below uses the data from "school.dat". It has a negative variance estimate, and I should probably add a third between-only variable. But it should be enough to demonstrate the problem.
```r
model <- '
level: within
fw =~ y6 + y7 + y8 + y9
level: between
fb =~ y6 + y7 + y8 + y9
fb2 =~ x3 + x4 '
fit <- sem(model, data = Data, cluster = "school")
out <- lavPredict(fit, level = 2)
cor(out) # lv correlation is 1
```
=> handle between-only ovs when predicting level 2 lvs

R/lav_partable_labels.R
For multigroup, multilevel models, the `group.equal` argument was being ignored due to some nested lists (for example, instead of a vector of ov.names for group 1, there was a list of length 2, containing within and between ov.names for group 1). This pull request fixes it so that something like `group.equal = "loadings"` constrains all loadings (within and between) to be equal across groups.
Here is an example of `group.equal` being ignored:
```r
model <- '
group: 1
level: within
fw =~ y1 + y2 + y3
level: between
fb =~ y1 + y2 + y3
group: 2
level: within
fw =~ y1 + y2 + y3
level: between
fb =~ y1 + y2 + y3
'
dtl <- Demo.twolevel
dtl$grp <- rep(c("a", "b"), each = nrow(dtl)/2)
fit <- cfa(model, data = dtl, cluster = "cluster", group = "grp", 
group.equal=c('intercepts', 'residuals'), …
```
=> fix group.equal for multigroup, multilevel models

R/lav_object_inspect.R
I left a comment on Lines 1399-1401 with some additional code to add a `block.label` even for single-block models, but I doubt that would ever be necessary.
=> don't name 1-block list in lavTech("rsquare"), fixes #290

R/lav_test_LRT.R
When I added this check last year, I didn't notice that the user-supplied `@external$h1` model would be ignored whenever a single model was passed to `lavTestLRT()`.  Now I check earlier and added a flag to only call `lav_test_lrt_single_model()` when `...` is empty AND when there is no user-supplied `@external$h1` model.
=> update LRT check for user-supplied h1

R/lav_fit_measures.R
lavaan's print methods never set `add.h0=TRUE`, so this will not affect lavaan output.  This is only to make lavaan.mi output look consistent with lavaan output.
=> Add header used in summary() by lavaan.mi

R/lav_fit_cfi.R
because multiple `test=` options might be printed, this place a comma between them
=> separate quoted tests in check_baseline() warning

R/lav_syntax_parser.R
Correction, there was an error if a comment contained a literal string, e.g. Y1 =~ X1 + X2 # this is "a tryout example" !
=> Update lav_syntax_parser.R (correction)

R/lav_fit_srmr.R, R/lav_model_h1_information.R, R/lav_model_utils.R, R/lav_object_inspect.R, R/lav_residuals.R, R/lav_standardize.R
These commits are only to add comments to source code that (if changed) could disrupt how lavaan.mi depends on lavaan to do the following:
- calculate `lavResiduals()`
- calculate `standardizedSolution()`
- calculate residual-based `fitMeasures()`
GitHub's diff-report makes it look like I changed the entire file, lav_object_inspect.R, when I only added 2 comments.  When I save a file in RStudio, my settings automatically remove trailing whitespace.  When I tell the diff report to ignore whitespace in RStudio, I verified that the only changes were the 2 added comments.
=> flagged source code lavaan.mi relies on

R/ctr_pml_plrt.R, R/lav_cfa_fabin.R, R/lav_cfa_guttman1952.R, R/lav_cfa_jamesstein.R, R/lav_data.R, R/lav_h1_implied.R, R/lav_lavaan_step01_ovnames.R, R/lav_lavaan_step09_model.R, R/lav_model.R, R/lav_modification.R, R/lav_msg.R, R/lav_object_inspect.R, R/lav_object_methods.R, R/lav_optim_noniter.R, R/lav_options.R, R/lav_options_estimator.R, R/lav_partable_bounds.R, R/lav_predict.R, R/lav_samplestats_gamma.R, R/lav_syntax_parser.R, R/lav_test.R
put error and warning msgs in one string to translate remove unused lav_msg_ functions, but give examples of use for the developper(s)
=> translator friendly changes

R/lav_lavaan_step00_init.R, R/lav_lavaan_step01_ovnames.R, R/lav_options_default.R, R/xxx_lavaan.R
functions also made much simpler: call lavaan() via  sys.call() and add model.type; defaults are set in lav_lavaan_step00_parameters() called in lavaan() lav_options_default(): add check for valid value of model.type remove unused parameter  lav_lavaan_step01_ovnames_group
=> seperate functions for cfa/sem and growth

R/00class.R, R/xxx_lavaanList.R, man/lavaanList-class.Rd
not sure why this slot was omitted, but I'd like to access it for lavaan.mi, which inherits from lavaanList
=> add @version slot to lavaanList-class, like lavaan

R/lav_lavaanList_methods.R, R/lav_lavaan_step17_lavaan.R, R/xxx_lavaanList.R
This preserves the version number as seen in `DESCRIPTION`, without replacing the hyphen by a period.
=> replace packageVersion() with packageDescription()

R/lav_print.R
The `$header` portion of `print.lavaan.summary()` is not all appropriate for a lavaan.mi object, and it uses some internal functions I cannot access.  To simplify this for the `lavaan.summary` object returned by `lavaan_mi_object_summary()`, I simply add a `$header.mi` element that is a character string to `cat()`.  When it is NULL, then nothing will be printed, so this doesn't interfere with the usual `print.lavaan.summary()` business.
=> print different header for lavaan.mi object

R/lav_predict.R
Hi Yves, here is a small issue I discovered in lavPredict() with ordinal variables.
The optimization step involves predictions from the standard normal cdf [here.](https://github.com/yrosseel/lavaan/blob/5029c2ba09631edf9d2ec31a9befcc1a77557511/R/lav_predict.R#L1857) This works most of the time because the lv mean (alpha) is usually fixed to 0. But it doesn't work when the lv mean is nonzero, which might happen in some multi-group models or in the silly model below that fixes the lv mean to 3. So the pull request explicitly centers the lvs by alpha before they get sent to the `pnorm()` lines.
```r
data(Science, package = 'mirt')
m1 <- ' f1 =~ Comfort + Work + Future + Benefit
f1 ~ 3*1 '
fit <- cfa(m1, data = Science, ordered = TRUE, std.lv = TRUE)
lvs <- lavPredict(fit)
summary(lvs[,1]) …
```
=> center ordinal lvs during lavPredict() optimization

R/lav_fit_measures.R
In lavaan.mi, I get the test from the `fitMeasures()` method, not a `short_summary()`.  So it took me a while to figure out a hack.  In the `$fit` elements header attribute, I give the header itself some attributes to hide some additional information for `print.lavaan.summary()` to find.  And the header's extra attributes are never printed because the `print.lavaan.vector()` method discards it before separately printing the header and vector.
=> lavaan.mi summary() prints test-pooling details

DESCRIPTION
This adds a link from the CRAN homepage, and makes the package findable on https://r-universe.dev
=> Advertise the bug tracker

R/lav_object_inspect.R, R/lav_object_methods.R
I’m working on some lavaan.mi functionality in `semTools::monteCarloCI()`, which requires the full `vcov()` for a standardized solution.  When I last visited, I worked out a hack for `standardizedSolution.mi()` by creating a fake lavaan object with pooled results inside it.  That object can also be passed to the workhorse:
```
lav_object_inspect_vcov(fit, standardized = TRUE, free.only = FALSE)
```
But that is not a public function.  I explored 2 possibilities to call it indirectly via public functions, both of which have a limitation I need to circumvent:
- Running `lavInspect(fit, "vcov.std.all")` only sets `free.only=TRUE`, without any way to pass more arguments via `...` because `lavInspect()` only has a `what=` argument.  It does not seem optimal to create even more `what=` options …
=> add vcov(standardized=, free.only=) arguments

R/lav_test.R, R/lav_test_LRT.R, R/lav_test_diff.R, R/lav_test_print.R
When I added `lav_update_test_custom_h1()` in PR #328, I set `$stat.group <- NULL` because when there is a more restricted `h1.model=`, the updated test is only available for the whole model.  This causes an error when `lav_test_print`ing multigroup models that have a hidden `@external$h1.model`.
```
HS.model <- '
visual  =~ x1 + x2 + x3
textual =~ x4 + x5 + x6
speed   =~ x7 + x8 + x9
'
fit1 <- cfa(HS.model, data = HolzingerSwineford1939, group = "school")
fit0 <- cfa(HS.model, data = HolzingerSwineford1939, group = "school", 
orthogonal = TRUE)
fit0@external$h1.model <- fit1
fit1 # prints group stats
fit0 # no group stats found, error
```
So I just added an additional condition in `lav_test_print()` to only print group stats `if (ngroups > 1L && !is.null(TEST[[block]]$stat.group))`.
=> lav_test_print() skips $stat.group when NULL

R/ctr_estfun.R
When estimating a model with fiml, only the scores of the first missingness-group are reported by lavScores. This is due to the seq_along function always evaluating to 1. I replaced seq_along with seq_len, which fixes the issue.
Example:
```
library(lavaan)
model <- ' 
ind60 =~ x1 + x2 + x3
dem60 =~ y1 + a*y2 + b*y3 + c*y4
dem65 =~ y5 + a*y6 + b*y7 + c*y8
dem60 ~ ind60
dem65 ~ ind60 + dem60
'
PoliticalDemocracy_NA <- PoliticalDemocracy
PoliticalDemocracy_NA[1:5, "x3"] <- NA
fit <- sem(model, 
data = PoliticalDemocracy_NA,
missing = "ml")
lavScores(fit) |>
head()
```
Note that the **first five lines are all zeros** because they are skipped in the for-loop.
=> Fix for missing scores in case of fiml.

R/lav_data.R, R/lav_dataframe.R, R/lav_muthen1984.R, R/lav_options_default.R, R/lav_samplestats.R, R/lav_samplestats_step1.R, man/lavOptions.Rd
This adds an extra option `allow.empty.cell`, which allows for ordinal variables that are missing some categories. This could involve an empty category in one group of a multi-group model, or a variable of class factor that (say) has 4 levels but only 3 are observed. My goal here is to have lavaan process these ordinal variables, so I can then model them in blavaan (where priors could compensate for the missing categories).
The default is `allow.empty.cell = FALSE`, where everything should work as usual.
For `allow.empty.cell = TRUE`, I had to set arbitrary starting values for the thresholds around empty categories. Assuming a variable with K categories, here is what I did:
Empty category 1: lower threshold -Inf, upper threshold -4
Empty category K: lower threshold 4, upper threshold Inf …
=> add option allow.empty.cell

R/lav_bvord.R, R/lav_data.R, R/lav_dataframe.R, R/lav_samplestats_step1.R, R/lav_uvord.R
This contains various improvements to the `allow.empty.cell` option from #377, including better consideration of multiple groups and missing data, and turning off some initial value computations that sometimes do not work for empty categories. This PR should only impact models where the user requests `allow.empty.cell = TRUE`. Improvements were aided by many examples from @jpritikin.
=> Improvements to allow.empty.cell

R/lav_syntax_parser.R, R/lav_syntax_parser_cr.R, R/lav_syntax_parser_r.R, R/ldw_trace.R
Add the checks for autoregression in R code (already present in C code).  Add an internal command summary_trace to retrieve count information from a trace.
=> add check for autoregression in R code;internal func summary_trace

R/lav_lavaan_step01_ovnames.R, R/lav_lavaan_step02_options.R, R/lav_model_compute.R, R/lav_model_information.R, R/lav_model_objective.R, R/lav_model_vcov.R, R/xxx_lavaan.R
Remove unused local variables in lav_lavaan_step01_ovnames.R, lav_model_compute.R, lav_model_information.R, lav_model_objective.R, lav_model_vcov.R. Correct erroneous line lav_lavaan_step02_options #155. Use default parser (from lav_options_default()) if not specified in lavaan().
=> Small corrections and remove some unused local variables.

R/lav_syntax_parser.R, R/lav_syntax_parser_r.R
Note: lavaanC is also updated to allow autoregression when the coefficient is fixed to zero.
=> Allow autoregression if coeff. fixed to zero

R/lav_matrix.R, R/lav_model_information.R
Order of execution for t(A) %*% B %*% A better if last product is performed first and if A is sparse a transponation + use of m_prod is faster than use of m_crossprod. Check for n > 0 before calling lavaanC::m_diag_idx.
=> better performance in lav_model_information

R/lav_sam_step1_local.R
The function get.JAC.veta2.fi() had a hardcoded dimension (4) that caused errors ("Error in block.b + long.b : non-conformable arrays") when a model had multiple endogenous latent variables where some had interactions/quadratic terms and others didn't. This fix replaces the hardcoded value with the dimension P.
=> Fix dimension mismatch in sam() with multiple endogenous variables for SE
