yrosseel/lavaan

- .Rbuildignore
- R/lav_partable_vnames.R
I only added  || inherits(object, "lavaanList") to line 11.  The file comparison shows 35 more changes throughout the file, but that is just a side effect of editing the file in RStudio, which has an option to delete any extra white space at the end of a line.
> lavNames(lavaanList)

- R/lav_simulate.R
Hi Yves,
Simple pull request which checks whether the *roots* of the required polynomials have been located rather than some potential *minimum*. It's possible for the `nlminb` optimiser to terminate successfully for some skew/kurtosis combinations, but that the solution doesn't actually contain roots, in which case a warning should be thrown. Cheers.
Phil
> Check that roots found in nlminb search for Vale & Maurelli polynomials

- man/lavOptions.Rd
> quotation marks

- R/lav_fit_measures.R
reported by a user on the lavaan forum:
https://groups.google.com/d/msg/lavaan/Rdxhuct-NCk/HIgmkEIwBgAJ
> update ifi.scaled formula

- R/ctr_mplus2lavaan.R
1. Allow .inp or .INP
2. Better support of expansion in constraint syntax
3. Support freed loadings without starting values. E.g., f1 by x1*
> mplus2lavaan bugfixes: improve parser for constraints and expansion etc.

- R/ctr_mplus2lavaan.R
> Escape hyphen in regular expression

- R/lav_object_methods.R
Closes #204 
Before:
``` r
library(lavaan)
#> This is lavaan 0.6-9.1634
#> lavaan is FREE software! Please report any bugs.
HS.model.labeled <- '
visual  =~ first*x1 + x2 + x3
textual =~ x4 + second*x5 + x6
speed   =~ x7 + x8 + third*x9'
fit.labeled <- cfa(HS.model.labeled, data=HolzingerSwineford1939)
parameterestimates(fit.labeled)
#>        lhs op     rhs  label   est    se      z pvalue ci.lower ci.upper
#> 1   visual =~      x1  first 1.000 0.000     NA     NA    1.000    1.000
#> 2   visual =~      x2        0.554 0.100  5.554      0    0.358    0.749
#> 3   visual =~      x3        0.729 0.109  6.685      0    0.516    0.943
#> 4  textual =~      x4        1.000 0.000     NA     NA    1.000    1.000
#> 5  textual =~      x5 second 1.113 0.065 17.014      0    0.985    1.241
#> 6 …
```
> add labels to standardizedSolution()

- README.md
Provides syntax highlighting for the code block and also a more modern font
> Switch to Markdown to get syntax highlighting

- man/bootstrap.Rd
requested on forum: https://groups.google.com/g/lavaan/c/9N4y9QNPX98/m/JTG9YKBUAQAJ
> add Value to boot man

- DESCRIPTION
- R/xxx_lavaan.R
I checked that it works and can more thoroughly debug as I develop the `lavaan.mi` package.  
FYI, `lavaan()` does not seem to "remember" when set `test = "Browne.residual.adf"`.  I can only get it directly from `lavTest()`, although the `?lavOptions` documentation seems to indicate any of those values would be recognized.
> make lavaan() check data= for "lavMoments" class

- man/model.syntax.Rd
Fixed typo in line 261; "in a similar why" -> "in a similar way"
> Fixed typo

- man/model.syntax.Rd
> add 4 operators to model.syntax.Rd

- .gitignore
- R/lav_syntax_parser.R
- lav_syntax_parser: better identification of interaction variables
- gitignore: added files to exclude when working on the project in Rstudio
> Correction in lav_syntax_parser

- R/lav_data.R
- R/xxx_lavaan.R
to simplify a bit the code in xxx_lavaan.R the timing maintenance is now done via function ldw_add_timing. typo in lav_data.R
> simplify xxx_lavaan.R timing

- R/lav_partable_vnames.R
- R/lav_syntax_parser.R
adjust warning in lav_syntax_parser.
correction small errors and optimalisation performance of lav_partable_vnames function.
> lav_partable_vnames rewritten

- NAMESPACE
- R/lav_predict_y.R
- man/cvLavPredictY.Rd
- man/lavPredictY.Rd
Added cvLavPredictY function to determine the value of the lambda penalty and updated the existing lavPredictY function to perform regularized out-of-sample prediction. Updated documentation to reflect this change. DOI pending in reference.
The below script can be used to verify that this regularized method can increase predictive accuracy. Let me know if you need another empirical example. Thank you!
```
library(lavaan)
library(semPlot)
data(PoliticalDemocracy)
pd <- PoliticalDemocracy
colnames(PoliticalDemocracy) = c("z1", "z2", "z3", "z4", "y1", "y2", "y3", "y4", "x1", "x2", "x3")
head(PoliticalDemocracy)
model0 <- '
ind60 =~ x1 + x2 + x3
dem60 =~ z1 + z2 + z3 + z4
dem65 =~ y1 + y2 + y3 + y4
dem60 ~ ind60
dem65 ~ ind60 + dem60
z1 ~~ y1
z2 ~~ z4 + y2
z3 ~~ y3
z4 ~~ y4
y2 ~~ y4
'
fit <- …
```
> Regularized out-of-sample SEM

- R/xxx_efa.R
If `data=` is a `lavMoments` object, then its `$sample.cov` element is now found when extracting `ov.names`
> efa() checks whether data= is lavMoments-class

- R/lav_model_h1_information.R
I looked at the code I contributed and it turns out there was just a single line to fix. Sorry for not doing this sooner!
> Remove pipes and \(x)

- R/lav_syntax_parser_cr.R
- R/lav_syntax_parser_r.R
Error (only in C++ for now) when trying to regress on itself. Check for group/level in C++ code.
> Change error/warnings if parser='c.r'

- R/lav_predict_y.R
Just happened to me out of careless and got error about singular system. Thought clear error message might be nice.
> check for duplicate variables names in lavPredict xnames and ynames
